set dotenv-load := true

serve:
    uvicorn main:app --reload --host 0.0.0.0 --port 8000

build-backend-data:
    python pipeline_builder.py
    
collect-course-materials:
    python -m init_utils.course_downloader

delete-course-materials:
    rm -rf $COURSE_MATERIALS_PATH

echo-vars:
    echo $COURSE_MATERIALS_PATH

format:
    black .

init-nltk:
    python init-utils/nltk_download.py

init-data-dirs:
    mkdir -p data/downloads